import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import localfont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const bigJohn = localfont({
  src: "../../public/font.otf",
  variable: "--font-big-jhon",
});

const FuturaBook = localfont({
  src: [
    {
      path: "../../public/fonts/futura-book.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/futura-book-italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/futura-book-medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/futura-book-medium-italic.ttf",
      weight: "500",
      style: "italic",
    },
    // {
    //   path: "../../public/fonts/futura-book-bold.ttf",
    //   weight: "700",
    //   style: "normal",
    // },
    {
      path: "../../public/fonts/futura-book-black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-futura-book",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${bigJohn.variable} ${FuturaBook.variable}`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
