import type { Metadata } from "next";
import { Instrument_Serif, Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import localfont from "next/font/local";
import "./globals.css";

const instrumentSerif = Instrument_Serif({ weight: "400", subsets: ["latin"] });

const bigJohn = localfont({
  src: "../../public/font.otf",
  variable: "--font-big-jhon",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${instrumentSerif.className} ${GeistSans.variable} ${bigJohn.variable}`}>
        {children}
      </body>
    </html>
  );
}
